# FightCountdown's configuration file
# -----
# defaultCount: the number /fight set beginns if no number is given
# maximumCountdown: the maximum the /fight set command can count down from. Use 0 to disable.
# announcementSchedule: the schedule announcements are made before the tournaments in minutes (15 means 15 minutes before the tournament starts).
# -----
# You may configure every message the plugin issues below.
# %time stands for the time, %arena for the arena and %host for the hoster of the tournament. They are defined in the tournaments.yml.
# %command stands for the given command.
# -----
defaultCount: 5
maximumCount: 15
announcementSchedule: 15, 30, 90, 150
announceTournament: You want to be a champion? Join the tournament on %time in the %arena and show what you can.
breakMessage: 'Countdown stopped!'
dice: 'Allowed weapon in this fight is %weapon!'
diceBow: 'a bow'
diceSword: 'an iron sword'
nextMessage: The next tournaments takes place on %time in the %arena. It's hosted by %host.
nextMessageNone: There are no tournaments at the moment.
reloadMessage: 'Configuration was successfully reloaded.'
startCountdown: 'Be ready, the fight starts in:'
startFight: 'Fight!'
needPermission: 'You do not have the permission to use %command!'