# FightCountdown's configuration file
# -----
# cleanTournaments: weather or not tournaments.yml should be sorted per date while old tournaments are removed.
# defaultCount: the number /fight set beginns if no number is given
# maximumCountdown: the maximum the /fight set command can count down from.
# announcementSchedule: the schedule announcements are made before the tournaments in minutes (15 means 15 minutes before the tournament starts).
# -----
# You may configure every message the plugin issues below.
# %time stands for the time, %arena for the arena and %host for the hoster of the tournament. They are defined in the tournaments.yml.
# %command stands for the given command.
# -----
cleanTournaments: true
defaultCount: 5
maximumCount: 15
announcementSchedule: 15, 30, 90, 150
dice:
- 'a bow'
- 'an iron sword'
announceTournament: You want to be a champion? Join the tournament on %time in the %arena and show what you can.
breakMessage: 'Countdown stopped!'
countdownRunning: 'There is already a countdown running.'
diceMessage: 'Allowed weapon in this fight is %weapon!'
needPermission: 'You do not have the permission to use %command!'
nextTournament: The next tournaments takes place on %time in the %arena. It's hosted by %host.
noPage: There is no page %page.
noTournaments: There are no tournaments at the moment.
tournamentList: '==============Tournaments, page %page of %totalPages ==============:'
tournamentListMask: '%date, takes place in %arena, hosted by %host'
reloadMessage: 'Configuration was successfully reloaded.'
startCountdown: 'Be ready, the fight starts in:'
startFight: 'Fight!'
wrongCountdown: 'The Countdown needs to be a number between 0 and %maximumCount.'