name: FightCountdown
main: de.minehattan.eduardbaer.FightCountdown.FightCountdown
version: 0.3
commands:
  fight:
    description: A simple countdown
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> <seconds>
