name: FightCountdown
main: de.minehattan.eduardbaer.FightCountdown.FightCountdown
version: 0.7
author: EduardBaer
website: www.github.com/EduardBaer/FightCountdown
commands:
  fight:
    description: A simple countdown
    usage: |
           Incorrect usage of /<command>. 
           See /<command> help for more information.
