name: FightCountdown
version: 0.7
description: A simple Bukkit plugin to set up a countdown for arena fights.
author: EduardBaer
website: www.github.com/EduardBaer/FightCountdown
main: de.minehattan.eduardbaer.FightCountdown.FightCountdown
commands:
  fight:
    aliases: fc
    description: A simple plugin to set up a countdown for arena fights.
    usage: |
           Incorrect usage of /<command>.
           See /<command> help for more information.
permissions:
    fightcountdown.*:
        description: Gives access to all fightcountdown commands
        children:
            fightcountdown.break: true
            fightcountdown.dice: true
            fightcountdown.next.clear : true
            fightcountdown.next.set : true
            fightcountdown.set: true
            fightcountdown.reload: true
    fightcountdown.break:
        description: Allows you to break the countdown from /fight set
        default: op
    fightcountdown.dice:
        description: Allows you to throw the dice to choose the weapon
        default: op
    fightcountdown.next.*:
        description: Allows you to clear and set the /fight next message
        children:
            fightcountdown.next.clear: true
            fightcountdown.next.set: true
    fightcountdown.next.set:
        description: Allows you to set the /fight next message
        default: op
    fightcountdown.next.clear:
        description: Allows you to clear the /fight next message
        default: op
    fightcountdown.set:
        description: Allows you to start a fight between users and set the countdown
        default: op
    fightcountdown.reload:
        description: Allows you to reload the configuration file
        default: op
