name: FightCountdown
version: 0.7
description: A simple Bukkit plugin to set up a countdown for arena fights.
author: EduardBaer
website: www.github.com/EduardBaer/FightCountdown
main: de.minehattan.eduardbaer.FightCountdown.FightCountdown
commands:
  fight:
    aliases: fc
    description: Does everything related to arena fights.
    usage: |
           Incorrect usage of /<command>.
           See /<command> help for more information.
  tournament:
    aliases: tm
    description: Does everything related to tournaments.
    usage: |
           Incorrect usage of /<command>.
           See /<command> help for more information.
permissions:
    fc.*:
        description: Gives access to all fightcountdown commands
        children:
            fc.reload: true
            fc.fight.break: true
            fc.fight.dice: true
            fc.fight.set: true
            fc.fight.set.bypass: true
            fc.fight.set.lightning: true
            fc.tournament.next: true
            fc.tournament.list: true
            fc.tournament.add: true
            fc.tournament.edit: true
            fc.tournament.remove: true
            fc.tournament.reload: true
    fc.fight:
        description: Gives access to all fight related commands
        children:
            fc.fight.break: true
            fc.fight.dice: true
            fc.fight.set: true
            fc.fight.set.bypass: true
            fc.fight.set.lightning: true
    fc.fight.user:
        description: Gives access to all harmless fight related commands
        children:
            fc.fight.break: true
            fc.fight.dice: true
            fc.fight.set: true
    fc.tournament:
        description: Gives access to all tournament related commands
        children:
            fc.tournament.next: true
            fc.tournament.list: true
            fc.tournament.add: true
            fc.tournament.edit: true
            fc.tournament.remove: true
            fc.tournament.reload: true
    fc.tournament.user:
        description: Gives access to all harmless tournament related commands
        children:
            fc.tournament.next: true
            fc.tournament.list: true
    fc.reload:
        description: Allows you to reload the configuration file
        default: op
        children:
            fc.tournament.reload: true
    fc.fight.break:
        description: Allows you to break the countdown from /fight set
        default: op
    fc.fight.dice:
        description: Allows you to throw the dice to choose the weapon
        default: op
    fc.fight.set:
        description: Allows you to start the countdown
        default: op
    fc.fight.set.bypass:
        description: Allows you to bypass the maximum countdown limit
        default: op
    fc.fight.set.lightning:
        description: Allows you to start the countdown and toggle a lightning when it ends
        default: op
    fc.tournament.next:
        description: Allows you to use /tournament next to see the date of next tournament
        default: op
    fc.tournament.list:
        description: Allows you to use /tournament list to see the list of future tournaments
        default: op
    fc.tournament.add:
        description: Allows you to add tournaments
        default: op
    fc.tournament.edit:
        description: Allows you to edit tournaments
        default: op
    fc.tournament.remove:
        description: Allows you to remove tournaments
        default: op
    fc.tournament.reload:
        description: Allows you to use reload the tournaments file
        default: op